/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;

import GymManagement_DB.GymManagementDB;
import activity.EmployeeClass;
import controller.EmployeeDAOimp;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import static java.lang.System.in;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import sun.misc.IOUtils;
import static sun.security.krb5.Confounder.bytes;

/**
 *
 * @author Wang
 */
public class employeeMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form memberMenu
     */
    int search;
    Blob filePath;
    public employeeMenu() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        Load();
        panelBorder();
        validationError();
        //Combo Gender
        jComboBox_EmpGender.setModel(new DefaultComboBoxModel<> (new String [] {
        "---Select Gender ---", "Male", "Female"}));
        //Combo Member Type
        jComboBox_StaffRole.setModel(new DefaultComboBoxModel<> (new String [] {
        "---Select Type ---", "Manager", "Front Desk", "Maintenance", "Guard"}));
        //Combo Member Type
        jComboBox_EmpShift.setModel(new DefaultComboBoxModel<> (new String [] {
        "---Select Status ---", "Morning", "Afternoon", "Night"}));
        
        txtField_EmployeeSalary.setEditable(false);
        
        tableSize ();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void tableSize () {
        
    jTable_employee.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
    
        for (int column = 0; column < jTable_employee.getColumnCount(); column++) {
            TableColumn tableColumn = jTable_employee.getColumnModel().getColumn(column);
//            int preferredWidth = tableColumn.getMinWidth();
            int preferredWidth = 100;
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < jTable_employee.getRowCount(); row++)
            {
                TableCellRenderer cellRenderer = jTable_employee.getCellRenderer(row, column);
                Component c = jTable_employee.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + jTable_employee.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth >= maxWidth)
                {
                    preferredWidth = maxWidth;
                    break;
                }
        }

        tableColumn.setPreferredWidth( preferredWidth );

        }      
    }
    
    private void Load() {
         EmployeeDAOimp employee_dao = new EmployeeDAOimp();
        List<EmployeeClass> list = employee_dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable_employee.getModel();
        DFT.setRowCount(0);
        for(EmployeeClass empc: list)
        {
            int id = empc.getId();
            int empID = empc.getEmployeeID();
            String first_name = empc.getFirstName();
            String middle_name = empc.getMiddleName();
            String last_name = empc.getLastName();
            String contact = empc.getContactNo();
            
            String birthday = empc.getBirthday();
            String emp_email = empc.getEmail();
            String gender = empc.getGender();
            String address = empc.getAddress();
            
            String staff_role = empc.getStaffRole();
            String shift = empc.getShift();
            
            double rate = empc.getRatePerHour();
            int hours = empc.getHoursWorked();
            double salary = empc.getSalary();
            DFT.addRow(new Object[]{id, empID, first_name, middle_name, last_name, contact, birthday, address,
            gender, emp_email, staff_role, shift, rate, hours, salary});
        }    
       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        employee_panel1 = new javax.swing.JPanel();
        lbl_EmployeeID = new javax.swing.JLabel();
        validation_empID = new javax.swing.JLabel();
        txtField_EmployeeID = new javax.swing.JTextField();
        jComboBox_StaffRole = new javax.swing.JComboBox<>();
        lbl_StaffRole = new javax.swing.JLabel();
        validation_role = new javax.swing.JLabel();
        lbl_EmployeeShift = new javax.swing.JLabel();
        validation_shift = new javax.swing.JLabel();
        jComboBox_EmpShift = new javax.swing.JComboBox<>();
        panel_fields = new javax.swing.JPanel();
        validation_contact = new javax.swing.JLabel();
        lbl_EmployeeFname = new javax.swing.JLabel();
        lbl_EmployeeContact = new javax.swing.JLabel();
        txtField_EmployeeContact = new javax.swing.JTextField();
        jDateChooser_EmpBirthday = new com.toedter.calendar.JDateChooser();
        validation_mname = new javax.swing.JLabel();
        validation_lname = new javax.swing.JLabel();
        txtField_EmployeeMname = new javax.swing.JTextField();
        lbl_EmployeeLname = new javax.swing.JLabel();
        validation_email = new javax.swing.JLabel();
        validation_birthday = new javax.swing.JLabel();
        txtField_EmployeeFname = new javax.swing.JTextField();
        txtField_EmployeeLname = new javax.swing.JTextField();
        lbl_EmployeeBirthday = new javax.swing.JLabel();
        txtField_EmployeeEmail = new javax.swing.JTextField();
        lbl_EmployeeMname = new javax.swing.JLabel();
        lbl_EmployeeEmail = new javax.swing.JLabel();
        validation_fname = new javax.swing.JLabel();
        panel_employee_list = new javax.swing.JPanel();
        txtField_EmployeeSearch = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jButton_EmpComputeSalary = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_employee = new javax.swing.JTable();
        panel_profile = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        btn_browse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_EmployeeRatePerHour = new javax.swing.JLabel();
        validation_rate = new javax.swing.JLabel();
        lbl_EmployeeSalary = new javax.swing.JLabel();
        lbl_EmployeeSalary1 = new javax.swing.JLabel();
        validation_salary = new javax.swing.JLabel();
        txtField_EmployeeSalary = new javax.swing.JTextField();
        txtField_EmployeeHoursWork = new javax.swing.JTextField();
        txtField_EmployeeRatePerHour = new javax.swing.JTextField();
        validation_hours = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_EmployeeGender = new javax.swing.JLabel();
        jComboBox_EmpGender = new javax.swing.JComboBox<>();
        txtField_EmployeeAddress = new javax.swing.JTextField();
        validation_address = new javax.swing.JLabel();
        validation_gender = new javax.swing.JLabel();
        lbl_EmployeeAddress = new javax.swing.JLabel();
        panel_buttons = new javax.swing.JPanel();
        jButton_EmpAdd = new javax.swing.JButton();
        jButton_EmpUpdate = new javax.swing.JButton();
        jButton_EmpDelete1 = new javax.swing.JButton();
        jButton_EmpClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 243, 246));

        jPanel1.setBackground(new java.awt.Color(254, 243, 246));

        employee_panel1.setBackground(new java.awt.Color(254, 243, 246));

        lbl_EmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeID.setText("Employee ID");

        validation_empID.setForeground(new java.awt.Color(255, 0, 51));
        validation_empID.setText("*");

        txtField_EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeIDActionPerformed(evt);
            }
        });

        jComboBox_StaffRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_StaffRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_StaffRole.setText("Staff Role");

        validation_role.setForeground(new java.awt.Color(255, 0, 51));
        validation_role.setText("*");

        lbl_EmployeeShift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeShift.setText("Shift");

        validation_shift.setForeground(new java.awt.Color(255, 0, 51));
        validation_shift.setText("*");

        jComboBox_EmpShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout employee_panel1Layout = new javax.swing.GroupLayout(employee_panel1);
        employee_panel1.setLayout(employee_panel1Layout);
        employee_panel1Layout.setHorizontalGroup(
            employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employee_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtField_EmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employee_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_StaffRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_role, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(employee_panel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_StaffRole, 0, 144, Short.MAX_VALUE)
                        .addGap(56, 56, 56)))
                .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_EmpShift, 0, 148, Short.MAX_VALUE)
                    .addGroup(employee_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        employee_panel1Layout.setVerticalGroup(
            employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panel1Layout.createSequentialGroup()
                .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeID)
                        .addComponent(validation_empID))
                    .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeShift)
                        .addComponent(validation_shift))
                    .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_StaffRole)
                        .addComponent(validation_role)))
                .addGap(10, 10, 10)
                .addGroup(employee_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_EmpShift, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtField_EmployeeID)
                    .addComponent(jComboBox_StaffRole))
                .addGap(6, 6, 6))
        );

        panel_fields.setBackground(new java.awt.Color(254, 243, 246));

        validation_contact.setForeground(new java.awt.Color(255, 0, 51));
        validation_contact.setText("*");

        lbl_EmployeeFname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeFname.setText("First Name");

        lbl_EmployeeContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeContact.setText("Contact No.");

        txtField_EmployeeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeContactActionPerformed(evt);
            }
        });

        jDateChooser_EmpBirthday.setDateFormatString("yyyy-MM-dd\n");

        validation_mname.setForeground(new java.awt.Color(255, 0, 51));
        validation_mname.setText("*");

        validation_lname.setForeground(new java.awt.Color(255, 0, 51));
        validation_lname.setText("*");

        txtField_EmployeeMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeMnameActionPerformed(evt);
            }
        });

        lbl_EmployeeLname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeLname.setText("Last Name");

        validation_email.setForeground(new java.awt.Color(255, 0, 51));
        validation_email.setText("*");

        validation_birthday.setForeground(new java.awt.Color(255, 0, 51));
        validation_birthday.setText("*");

        txtField_EmployeeFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeFnameActionPerformed(evt);
            }
        });

        txtField_EmployeeLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeLnameActionPerformed(evt);
            }
        });

        lbl_EmployeeBirthday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeBirthday.setText("Birthday");

        txtField_EmployeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeEmailActionPerformed(evt);
            }
        });

        lbl_EmployeeMname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeMname.setText("Middle Name");

        lbl_EmployeeEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeEmail.setText("Email");

        validation_fname.setForeground(new java.awt.Color(255, 0, 51));
        validation_fname.setText("*");

        javax.swing.GroupLayout panel_fieldsLayout = new javax.swing.GroupLayout(panel_fields);
        panel_fields.setLayout(panel_fieldsLayout);
        panel_fieldsLayout.setHorizontalGroup(
            panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fieldsLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addComponent(lbl_EmployeeContact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtField_EmployeeContact)
                            .addComponent(txtField_EmployeeFname, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fieldsLayout.createSequentialGroup()
                                .addComponent(lbl_EmployeeFname)
                                .addGap(3, 3, 3)
                                .addComponent(validation_fname)))
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                                        .addComponent(lbl_EmployeeMname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validation_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtField_EmployeeMname, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                                        .addComponent(lbl_EmployeeBirthday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validation_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser_EmpBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addComponent(lbl_EmployeeLname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_EmployeeEmail)
                            .addComponent(txtField_EmployeeLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(lbl_EmployeeEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation_email, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panel_fieldsLayout.setVerticalGroup(
            panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fieldsLayout.createSequentialGroup()
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(validation_fname)
                        .addComponent(lbl_EmployeeFname))
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeLname)
                        .addComponent(validation_lname)
                        .addComponent(lbl_EmployeeMname)
                        .addComponent(validation_mname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtField_EmployeeMname, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(txtField_EmployeeFname, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(txtField_EmployeeLname, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeContact)
                        .addComponent(validation_contact))
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeBirthday)
                        .addComponent(validation_birthday)
                        .addComponent(lbl_EmployeeEmail)
                        .addComponent(validation_email)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtField_EmployeeContact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_EmpBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtField_EmployeeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_employee_list.setBackground(new java.awt.Color(254, 243, 246));

        txtField_EmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeSearchActionPerformed(evt);
            }
        });

        jButton_search.setBackground(new java.awt.Color(223, 89, 62));
        jButton_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/search.png"))); // NOI18N
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jButton_EmpComputeSalary.setText("Compute Salary");
        jButton_EmpComputeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpComputeSalaryActionPerformed(evt);
            }
        });

        jTable_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee ID", "First Name", "Middle Name", "Last Name", "Contact No", "Brthday", "Email", "Gender", "Address", "Staff Role", "Shift", "Rate Per Hour", "Hours Worked", "Salary"
            }
        ));
        jTable_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_employeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_employee);

        javax.swing.GroupLayout panel_employee_listLayout = new javax.swing.GroupLayout(panel_employee_list);
        panel_employee_list.setLayout(panel_employee_listLayout);
        panel_employee_listLayout.setHorizontalGroup(
            panel_employee_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employee_listLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_employee_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_employee_listLayout.createSequentialGroup()
                        .addComponent(txtField_EmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jButton_EmpComputeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_employee_listLayout.setVerticalGroup(
            panel_employee_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_employee_listLayout.createSequentialGroup()
                .addGroup(panel_employee_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_EmpComputeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_EmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_profile.setLayout(new java.awt.GridBagLayout());

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/profile.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        panel_profile.add(lbl_image, gridBagConstraints);

        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 10);
        panel_profile.add(btn_browse, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(254, 243, 246));

        lbl_EmployeeRatePerHour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeRatePerHour.setText("Rate Per Hour");

        validation_rate.setForeground(new java.awt.Color(255, 0, 51));
        validation_rate.setText("*");

        lbl_EmployeeSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeSalary.setText("Hours Worked");

        lbl_EmployeeSalary1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeSalary1.setText("Salary");

        validation_salary.setForeground(new java.awt.Color(255, 0, 51));
        validation_salary.setText("*");

        txtField_EmployeeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeSalaryActionPerformed(evt);
            }
        });

        txtField_EmployeeHoursWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeHoursWorkActionPerformed(evt);
            }
        });

        txtField_EmployeeRatePerHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeRatePerHourActionPerformed(evt);
            }
        });

        validation_hours.setForeground(new java.awt.Color(255, 0, 51));
        validation_hours.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeRatePerHour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtField_EmployeeRatePerHour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeSalary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtField_EmployeeHoursWork, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeSalary1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtField_EmployeeSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeSalary)
                        .addComponent(validation_hours))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeRatePerHour)
                        .addComponent(validation_rate))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeSalary1)
                        .addComponent(validation_salary)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtField_EmployeeHoursWork, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtField_EmployeeRatePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtField_EmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(254, 243, 246));

        lbl_EmployeeGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeGender.setText("Gender");

        jComboBox_EmpGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_EmpGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EmpGenderActionPerformed(evt);
            }
        });

        txtField_EmployeeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_EmployeeAddressActionPerformed(evt);
            }
        });

        validation_address.setForeground(new java.awt.Color(255, 0, 51));
        validation_address.setText("*");

        validation_gender.setForeground(new java.awt.Color(255, 0, 51));
        validation_gender.setText("*");

        lbl_EmployeeAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeAddress.setText("Address");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_EmployeeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_address, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtField_EmployeeAddress))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeGender)
                        .addComponent(validation_gender))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeAddress)
                        .addComponent(validation_address)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_EmployeeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        panel_buttons.setBackground(new java.awt.Color(0, 212, 212));

        jButton_EmpAdd.setBackground(new java.awt.Color(0, 181, 73));
        jButton_EmpAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_EmpAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/add.png"))); // NOI18N
        jButton_EmpAdd.setText("ADD");
        jButton_EmpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpAddActionPerformed(evt);
            }
        });

        jButton_EmpUpdate.setBackground(new java.awt.Color(79, 118, 224));
        jButton_EmpUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_EmpUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/update.png"))); // NOI18N
        jButton_EmpUpdate.setText("UPDATE");
        jButton_EmpUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpUpdateActionPerformed(evt);
            }
        });

        jButton_EmpDelete1.setBackground(new java.awt.Color(174, 13, 16));
        jButton_EmpDelete1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_EmpDelete1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/delete.png"))); // NOI18N
        jButton_EmpDelete1.setText("DELETE");
        jButton_EmpDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpDelete1ActionPerformed(evt);
            }
        });

        jButton_EmpClear.setBackground(new java.awt.Color(240, 194, 0));
        jButton_EmpClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_EmpClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/clear.png"))); // NOI18N
        jButton_EmpClear.setText("CLEAR");
        jButton_EmpClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_buttonsLayout = new javax.swing.GroupLayout(panel_buttons);
        panel_buttons.setLayout(panel_buttonsLayout);
        panel_buttonsLayout.setHorizontalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_EmpAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_EmpUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_EmpDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_EmpClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_buttonsLayout.setVerticalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_EmpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_EmpUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_EmpDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_EmpClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_employee_list, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_fields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employee_panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(employee_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_employee_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EmpClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpClearActionPerformed
        EmployeeClass employee = new EmployeeClass();        
        Load();
        txtField_EmployeeID.setText("");
        txtField_EmployeeFname.setText("");
        txtField_EmployeeMname.setText("");
        txtField_EmployeeLname.setText("");
        txtField_EmployeeContact.setText("");
        txtField_EmployeeEmail.setText("");
        txtField_EmployeeAddress.setText("");
        txtField_EmployeeSalary.setText("");
        txtField_EmployeeRatePerHour.setText("");
        txtField_EmployeeHoursWork.setText("");
        txtField_EmployeeSearch.setText("");

        jComboBox_StaffRole.setSelectedItem(null);
        jComboBox_EmpShift.setSelectedItem(null);
        jComboBox_EmpGender.setSelectedItem(null);

        jDateChooser_EmpBirthday.setCalendar(null);
        
        ImageIcon defaultImg = new ImageIcon(employeeMenu.class.getResource("images/profile.png"));
        lbl_image.setIcon(defaultImg);
        validationError();
    }//GEN-LAST:event_jButton_EmpClearActionPerformed

    private void jButton_EmpDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpDelete1ActionPerformed
        EmployeeClass employee = new EmployeeClass();

        employee.setId(search);
        EmployeeDAOimp employee_dao = new EmployeeDAOimp();
        employee_dao.delete(employee);
        Load();
        txtField_EmployeeID.setText("");
        txtField_EmployeeFname.setText("");
        txtField_EmployeeMname.setText("");
        txtField_EmployeeLname.setText("");
        txtField_EmployeeContact.setText("");
        txtField_EmployeeEmail.setText("");
        txtField_EmployeeAddress.setText("");
        txtField_EmployeeRatePerHour.setText("");
        txtField_EmployeeHoursWork.setText("");
        txtField_EmployeeSalary.setText("");

        jComboBox_StaffRole.setSelectedIndex(0);
        jComboBox_EmpShift.setSelectedIndex(0);
        jComboBox_EmpGender.setSelectedIndex(0);

        jDateChooser_EmpBirthday.setCalendar(null);

        txtField_EmployeeID.requestFocus();
    }//GEN-LAST:event_jButton_EmpDelete1ActionPerformed

    private void jButton_EmpUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpUpdateActionPerformed
        try{
            EmployeeClass employee = new EmployeeClass();
            int employee_id = Integer.parseInt(txtField_EmployeeID.getText());
            String employee_first_name = txtField_EmployeeFname.getText();
            String employee_middle_name = txtField_EmployeeMname.getText();
            String employee_last_name = txtField_EmployeeLname.getText();
            String employee_contact = txtField_EmployeeContact.getText();

            String employee_birthday = ((JTextField) jDateChooser_EmpBirthday.getDateEditor().getUiComponent()).getText();

            String employee_email = txtField_EmployeeEmail.getText();
            String employee_gender = jComboBox_EmpGender.getSelectedItem().toString();
            String employee_address = txtField_EmployeeAddress.getText();
            String staff_role = jComboBox_StaffRole.getSelectedItem().toString();
            String shift = jComboBox_EmpShift.getSelectedItem().toString();

            double employee_rate = Double.parseDouble(txtField_EmployeeRatePerHour.getText());
            int employee_hours = Integer.parseInt(txtField_EmployeeHoursWork.getText());

            double salary = Double.parseDouble(txtField_EmployeeSalary.getText());
            

            employee.setEmployeeID(employee_id);
            employee.setFirstName(employee_first_name);
            employee.setMiddleName(employee_middle_name);
            employee.setLastName(employee_last_name);
            employee.setContactNo(employee_contact);
            employee.setBirthday(employee_birthday);
            employee.setEmail(employee_email);
            employee.setGender(employee_gender);
            employee.setAddress(employee_address);
            employee.setStaffRole(staff_role);
            employee.setShift(shift);
            employee.setRatePerHour(employee_rate);
            employee.setHoursWorked(employee_hours);
            employee.setTotal(salary);
            employee.setImage(pimage);
            employee.setId(search);
            
            EmployeeDAOimp employee_dao = new EmployeeDAOimp();
            employee_dao.update(employee);
            Load();
            

            txtField_EmployeeID.setText("");
            txtField_EmployeeFname.setText("");
            txtField_EmployeeMname.setText("");
            txtField_EmployeeLname.setText("");
            txtField_EmployeeContact.setText("");
            txtField_EmployeeEmail.setText("");
            txtField_EmployeeAddress.setText("");
            txtField_EmployeeRatePerHour.setText("");
            txtField_EmployeeHoursWork.setText("");
            txtField_EmployeeSalary.setText("");

            jComboBox_StaffRole.setSelectedIndex(0);
            jComboBox_EmpShift.setSelectedIndex(0);
            jComboBox_EmpGender.setSelectedIndex(0);

            jDateChooser_EmpBirthday.setCalendar(null);

            ImageIcon defaultImg = new ImageIcon(employeeMenu.class.getResource("images/profile.png"));
            lbl_image.setIcon(defaultImg);   
            
            txtField_EmployeeID.requestFocus();            
            validationError();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
    }//GEN-LAST:event_jButton_EmpUpdateActionPerformed

    private void jButton_EmpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpAddActionPerformed

        try{
        if(txtField_EmployeeID.getText().trim().isEmpty()){
            validation_empID.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Employee ID!");
            return;
        }
        
        if(txtField_EmployeeFname.getText().trim().isEmpty()){
            validation_fname.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter First Name!");
            return;
        }  
        
        if(txtField_EmployeeMname.getText().trim().isEmpty()){
            validation_mname.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Middle Name!");
            return;
        }
        
        if(txtField_EmployeeLname.getText().trim().isEmpty()){
            validation_lname.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Last Name!");
            return;
        }
        
        if(txtField_EmployeeContact.getText().trim().isEmpty()){
            validation_contact.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Contact!");
            return;
        }
        
         if(((JTextField)jDateChooser_EmpBirthday.getDateEditor().getUiComponent()).getText().isEmpty()){
            validation_birthday.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Birthday!");
            return;
        }       

        if(txtField_EmployeeEmail.getText().trim().isEmpty()){
            validation_email.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Email!");
            return;
        }         

        if(txtField_EmployeeAddress.getText().trim().isEmpty()){          
            validation_address.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Address!");
            return;
        }
        
        if(txtField_EmployeeRatePerHour.getText().trim().isEmpty()){          
            validation_rate.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Rate Per Hour!");
            return;
        }
        
        if(txtField_EmployeeHoursWork.getText().trim().isEmpty()){
            validation_hours.setVisible(true);
            JOptionPane.showMessageDialog(null, "Enter Hours Work!");
            return;
        }
        
        if(jComboBox_StaffRole.getSelectedIndex()==0){
            validation_role.setVisible(true);
            JOptionPane.showMessageDialog(null, "Select Staff Role!");
            return;
        }
        
        if(jComboBox_EmpShift.getSelectedIndex()==0){
            validation_shift.setVisible(true);
            JOptionPane.showMessageDialog(null, "Select Shift!");
            return;
        }
        
        if(jComboBox_EmpGender.getSelectedIndex()==0){
            validation_gender.setVisible(true);
            JOptionPane.showMessageDialog(null, "Select Gender!");
            return;
        }


        else{
            
           EmployeeClass employee = new EmployeeClass();
           employee.ComputeSalary();
           int employee_id = Integer.parseInt(txtField_EmployeeID.getText());
           String employee_first_name = txtField_EmployeeFname.getText();
           String employee_middle_name = txtField_EmployeeMname.getText();
           String employee_last_name = txtField_EmployeeLname.getText();
           String employee_contact = txtField_EmployeeContact.getText();

           String employee_birthday = ((JTextField) jDateChooser_EmpBirthday.getDateEditor().getUiComponent()).getText();

           String employee_email = txtField_EmployeeEmail.getText();
           String employee_gender = jComboBox_EmpGender.getSelectedItem().toString();
           String employee_address = txtField_EmployeeAddress.getText();
           String employee_role = jComboBox_StaffRole.getSelectedItem().toString();
           String employee_shift = jComboBox_EmpShift.getSelectedItem().toString();
           int employee_hours = Integer.parseInt(txtField_EmployeeHoursWork.getText());
           double employee_rate = Double.parseDouble(txtField_EmployeeRatePerHour.getText());
           double employee_salary = Double.parseDouble(txtField_EmployeeSalary.getText());


           employee.setEmployeeID(employee_id);
           employee.setFirstName(employee_first_name);
           employee.setMiddleName(employee_middle_name);
           employee.setLastName(employee_last_name);
           employee.setGender(employee_gender);
           employee.setBirthday(employee_birthday);
           employee.setContactNo(employee_contact);
           employee.setEmail(employee_email);
           employee.setAddress(employee_address);
           employee.setStaffRole(employee_role);
           employee.setShift(employee_shift);
           employee.setHoursWorked(employee_hours);
           employee.setRatePerHour(employee_rate);
           employee.setTotal(employee_salary);

           employee.setImage(pimage);


           EmployeeDAOimp employee_dao = new EmployeeDAOimp();
           employee_dao.save(employee);


           Load();

           txtField_EmployeeID.setText("");
           txtField_EmployeeFname.setText("");
           txtField_EmployeeMname.setText("");
           txtField_EmployeeLname.setText("");
           txtField_EmployeeContact.setText("");
           txtField_EmployeeEmail.setText("");
           txtField_EmployeeAddress.setText("");
           txtField_EmployeeSalary.setText("");
           txtField_EmployeeRatePerHour.setText("");
           txtField_EmployeeHoursWork.setText("");

           jComboBox_StaffRole.setSelectedItem(null);
           jComboBox_EmpShift.setSelectedItem(null);
           jComboBox_EmpGender.setSelectedItem(null);

           jDateChooser_EmpBirthday.setCalendar(null);

           txtField_EmployeeID.requestFocus();

           ImageIcon defaultImg = new ImageIcon(employeeMenu.class.getResource("images/profile.png"));
           lbl_image.setIcon(defaultImg);        
           validationError();           
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Complete the form!");
      }
        

    }//GEN-LAST:event_jButton_EmpAddActionPerformed

    private void txtField_EmployeeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeAddressActionPerformed

    private void jComboBox_EmpGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EmpGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EmpGenderActionPerformed

    private void txtField_EmployeeRatePerHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeRatePerHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeRatePerHourActionPerformed

    private void txtField_EmployeeHoursWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeHoursWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeHoursWorkActionPerformed

    private void txtField_EmployeeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeSalaryActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtField_EmployeeSalaryActionPerformed
    
    File f;
    String path;
    byte[] pimage=null;
    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
    
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(path);
        
        try {
            File imageProfile=new File(path);
            FileInputStream fis=new FileInputStream(imageProfile);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                
            }
            pimage=baos.toByteArray();
            Image image = micon.getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
            lbl_image.setIcon(new ImageIcon(image)); 
        } catch (Exception e) {
        }               
        

    }//GEN-LAST:event_btn_browseActionPerformed

    private void jTable_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_employeeMouseClicked
        try {

            DefaultTableModel RecordTable = (DefaultTableModel)jTable_employee.getModel();
            int SelectedRows = jTable_employee.getSelectedRow();
            EmployeeDAOimp dao = new EmployeeDAOimp ();

            search = (int) (jTable_employee.getModel().getValueAt(SelectedRows, 0));
            EmployeeClass empc = dao.get(search);

            txtField_EmployeeID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
            txtField_EmployeeFname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
            txtField_EmployeeMname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
            txtField_EmployeeLname.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
            txtField_EmployeeContact.setText(RecordTable.getValueAt(SelectedRows, 5).toString());

            Date dateBirth = new SimpleDateFormat ("yyyy-MM-dd").parse((String)RecordTable.getValueAt(SelectedRows, 6));
            jDateChooser_EmpBirthday.setDate(dateBirth);

            txtField_EmployeeEmail.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
            jComboBox_EmpGender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
            txtField_EmployeeAddress.setText(RecordTable.getValueAt(SelectedRows, 9).toString());

            jComboBox_StaffRole.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10).toString());
            jComboBox_EmpShift.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11).toString());

            txtField_EmployeeRatePerHour.setText(RecordTable.getValueAt(SelectedRows, 12).toString());
            txtField_EmployeeHoursWork.setText(RecordTable.getValueAt(SelectedRows, 13).toString());
            txtField_EmployeeSalary.setText(RecordTable.getValueAt(SelectedRows, 14).toString());
            

            
            pimage = empc.getImage();
            
   
            ImageIcon icon = new ImageIcon(pimage);
            Image image = icon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH);
            lbl_image.setIcon(new ImageIcon(image));
            
            Load();

        } catch (ParseException ex) {
            Logger.getLogger(employeeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_employeeMouseClicked

    private void jButton_EmpComputeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpComputeSalaryActionPerformed
        EmployeeClass employee = new EmployeeClass();
        employee.setRatePerHour(Double.parseDouble(txtField_EmployeeRatePerHour.getText()));
        employee.setHoursWorked(Integer.parseInt(txtField_EmployeeHoursWork.getText()));
        employee.ComputeSalary();
        txtField_EmployeeSalary.setText(employee.getSalary()+"");
    }//GEN-LAST:event_jButton_EmpComputeSalaryActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        try{

            search = Integer.parseInt(txtField_EmployeeSearch.getText());
            EmployeeDAOimp dao = new EmployeeDAOimp ();
            EmployeeClass empc = dao.get(search);

            txtField_EmployeeID.setText(String.valueOf(empc.getEmployeeID()));
            txtField_EmployeeFname.setText(empc.getFirstName());
            txtField_EmployeeMname.setText(empc.getMiddleName());
            txtField_EmployeeLname.setText(empc.getLastName());
            txtField_EmployeeContact.setText(String.valueOf(empc.getContactNo()));
            txtField_EmployeeEmail.setText(empc.getEmail());
            txtField_EmployeeAddress.setText(empc.getAddress());
            txtField_EmployeeRatePerHour.setText(String.valueOf(empc.getRatePerHour()));
            txtField_EmployeeHoursWork.setText(String.valueOf(empc.getHoursWorked()));
            txtField_EmployeeSalary.setText(String.valueOf(empc.getTotal()));
            

            jComboBox_StaffRole.setSelectedItem(empc.getStaffRole());
            jComboBox_EmpShift.setSelectedItem(empc.getShift());
            jComboBox_EmpGender.setSelectedItem(empc.getGender());

            Date dateBirth = new SimpleDateFormat ("yyyy-MM-dd").parse(String.valueOf(empc.getBirthday()));

            jDateChooser_EmpBirthday.setDate(dateBirth);
            
            pimage = empc.getImage();
            
   
            ImageIcon icon = new ImageIcon(pimage);
            Image image = icon.getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH);
            lbl_image.setIcon(new ImageIcon(image));            

            Load();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "No Result!");
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void txtField_EmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeSearchActionPerformed

    private void txtField_EmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeEmailActionPerformed

    private void txtField_EmployeeLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeLnameActionPerformed

    private void txtField_EmployeeFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeFnameActionPerformed

    private void txtField_EmployeeMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeMnameActionPerformed

    private void txtField_EmployeeContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeContactActionPerformed

    private void txtField_EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_EmployeeIDActionPerformed
   
    

    
    private void validationError() {
            validation_empID.setVisible(false);
            validation_address.setVisible(false);
            validation_role.setVisible(false);
            validation_shift.setVisible(false);
            validation_fname.setVisible(false);
            validation_birthday.setVisible(false);
            validation_hours.setVisible(false);
            validation_mname.setVisible(false);
            validation_contact.setVisible(false);
            validation_rate.setVisible(false);
            validation_lname.setVisible(false);
            validation_email.setVisible(false);
            validation_salary.setVisible(false);
            validation_gender.setVisible(false);
    }
    
    
    public void panelBorder(){
        
       panel_employee_list.setBorder(new TitledBorder(new LineBorder(new Color (16, 82, 142)), 
                "Employee List", TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.CENTER, new Font("SansSerif", Font.PLAIN, 12), new Color (16, 82, 142)));
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_browse;
    private javax.swing.JPanel employee_panel1;
    private javax.swing.JButton jButton_EmpAdd;
    private javax.swing.JButton jButton_EmpClear;
    private javax.swing.JButton jButton_EmpComputeSalary;
    private javax.swing.JButton jButton_EmpDelete1;
    private javax.swing.JButton jButton_EmpUpdate;
    private javax.swing.JButton jButton_search;
    private javax.swing.JComboBox<String> jComboBox_EmpGender;
    private javax.swing.JComboBox<String> jComboBox_EmpShift;
    private javax.swing.JComboBox<String> jComboBox_StaffRole;
    private com.toedter.calendar.JDateChooser jDateChooser_EmpBirthday;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_employee;
    private javax.swing.JLabel lbl_EmployeeAddress;
    private javax.swing.JLabel lbl_EmployeeBirthday;
    private javax.swing.JLabel lbl_EmployeeContact;
    private javax.swing.JLabel lbl_EmployeeEmail;
    private javax.swing.JLabel lbl_EmployeeFname;
    private javax.swing.JLabel lbl_EmployeeGender;
    private javax.swing.JLabel lbl_EmployeeID;
    private javax.swing.JLabel lbl_EmployeeLname;
    private javax.swing.JLabel lbl_EmployeeMname;
    private javax.swing.JLabel lbl_EmployeeRatePerHour;
    private javax.swing.JLabel lbl_EmployeeSalary;
    private javax.swing.JLabel lbl_EmployeeSalary1;
    private javax.swing.JLabel lbl_EmployeeShift;
    private javax.swing.JLabel lbl_StaffRole;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JPanel panel_employee_list;
    private javax.swing.JPanel panel_fields;
    private javax.swing.JPanel panel_profile;
    private javax.swing.JTextField txtField_EmployeeAddress;
    private javax.swing.JTextField txtField_EmployeeContact;
    private javax.swing.JTextField txtField_EmployeeEmail;
    private javax.swing.JTextField txtField_EmployeeFname;
    private javax.swing.JTextField txtField_EmployeeHoursWork;
    private javax.swing.JTextField txtField_EmployeeID;
    private javax.swing.JTextField txtField_EmployeeLname;
    private javax.swing.JTextField txtField_EmployeeMname;
    private javax.swing.JTextField txtField_EmployeeRatePerHour;
    private javax.swing.JTextField txtField_EmployeeSalary;
    private javax.swing.JTextField txtField_EmployeeSearch;
    private javax.swing.JLabel validation_address;
    private javax.swing.JLabel validation_birthday;
    private javax.swing.JLabel validation_contact;
    private javax.swing.JLabel validation_email;
    private javax.swing.JLabel validation_empID;
    private javax.swing.JLabel validation_fname;
    private javax.swing.JLabel validation_gender;
    private javax.swing.JLabel validation_hours;
    private javax.swing.JLabel validation_lname;
    private javax.swing.JLabel validation_mname;
    private javax.swing.JLabel validation_rate;
    private javax.swing.JLabel validation_role;
    private javax.swing.JLabel validation_salary;
    private javax.swing.JLabel validation_shift;
    // End of variables declaration//GEN-END:variables

    

   
}
