/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Wang
 */
public class Home extends javax.swing.JFrame {
 
    int xMouse;
    int yMouse;
    
    public Home() {
        initComponents();
        setIconImage();
        
    }
    
/**
     * Creates new form Home
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        btn_gymMembers = new javax.swing.JPanel();
        icon_members = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_instructor = new javax.swing.JPanel();
        icon_members4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_employee = new javax.swing.JPanel();
        icon_members5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_equipment = new javax.swing.JPanel();
        icon_members6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnl_GymMembers = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnl_Header = new javax.swing.JPanel();
        header_title = new javax.swing.JLabel();
        header_title1 = new javax.swing.JLabel();
        pnl_Header1 = new javax.swing.JPanel();
        header_tab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym Management System");

        bg.setBackground(new java.awt.Color(0, 212, 212));

        sidepanel.setBackground(new java.awt.Color(251, 126, 100));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_gymMembers.setBackground(new java.awt.Color(251, 126, 100));
        btn_gymMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gymMembersMouseClicked(evt);
            }
        });

        icon_members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_members.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/members_icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gym Members");

        javax.swing.GroupLayout btn_gymMembersLayout = new javax.swing.GroupLayout(btn_gymMembers);
        btn_gymMembers.setLayout(btn_gymMembersLayout);
        btn_gymMembersLayout.setHorizontalGroup(
            btn_gymMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_gymMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_members)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        btn_gymMembersLayout.setVerticalGroup(
            btn_gymMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_members, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btn_gymMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 60));

        btn_instructor.setBackground(new java.awt.Color(251, 126, 100));
        btn_instructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_instructorMouseClicked(evt);
            }
        });

        icon_members4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_members4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/instructor_icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Instructor");

        javax.swing.GroupLayout btn_instructorLayout = new javax.swing.GroupLayout(btn_instructor);
        btn_instructor.setLayout(btn_instructorLayout);
        btn_instructorLayout.setHorizontalGroup(
            btn_instructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_instructorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_members4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        btn_instructorLayout.setVerticalGroup(
            btn_instructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_members4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btn_instructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, -1));

        btn_employee.setBackground(new java.awt.Color(251, 126, 100));
        btn_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_employeeMouseClicked(evt);
            }
        });

        icon_members5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_members5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/employee_icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee");

        javax.swing.GroupLayout btn_employeeLayout = new javax.swing.GroupLayout(btn_employee);
        btn_employee.setLayout(btn_employeeLayout);
        btn_employeeLayout.setHorizontalGroup(
            btn_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_employeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_members5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        btn_employeeLayout.setVerticalGroup(
            btn_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_members5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btn_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, -1));

        btn_equipment.setBackground(new java.awt.Color(251, 126, 100));
        btn_equipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_equipmentMouseClicked(evt);
            }
        });

        icon_members6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_members6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/equipment_icon.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Equipment");

        javax.swing.GroupLayout btn_equipmentLayout = new javax.swing.GroupLayout(btn_equipment);
        btn_equipment.setLayout(btn_equipmentLayout);
        btn_equipmentLayout.setHorizontalGroup(
            btn_equipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_equipmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_members6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        btn_equipmentLayout.setVerticalGroup(
            btn_equipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_members6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel.add(btn_equipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, -1));

        pnl_GymMembers.setBackground(new java.awt.Color(254, 243, 246));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/gymhome.png"))); // NOI18N

        pnl_Header.setBackground(new java.awt.Color(254, 243, 246));

        header_title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        header_title.setForeground(new java.awt.Color(251, 126, 100));
        header_title.setText("GYM");

        header_title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        header_title1.setForeground(new java.awt.Color(251, 126, 100));
        header_title1.setText("Management System");

        javax.swing.GroupLayout pnl_HeaderLayout = new javax.swing.GroupLayout(pnl_Header);
        pnl_Header.setLayout(pnl_HeaderLayout);
        pnl_HeaderLayout.setHorizontalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_HeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(header_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header_title1)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        pnl_HeaderLayout.setVerticalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(header_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header_title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_GymMembersLayout = new javax.swing.GroupLayout(pnl_GymMembers);
        pnl_GymMembers.setLayout(pnl_GymMembersLayout);
        pnl_GymMembersLayout.setHorizontalGroup(
            pnl_GymMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GymMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_GymMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_GymMembersLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_GymMembersLayout.setVerticalGroup(
            pnl_GymMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GymMembersLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pnl_Header1.setBackground(new java.awt.Color(251, 126, 100));

        header_tab.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header_tab.setForeground(new java.awt.Color(255, 255, 255));
        header_tab.setText("HOME");

        javax.swing.GroupLayout pnl_Header1Layout = new javax.swing.GroupLayout(pnl_Header1);
        pnl_Header1.setLayout(pnl_Header1Layout);
        pnl_Header1Layout.setHorizontalGroup(
            pnl_Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_tab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Header1Layout.setVerticalGroup(
            pnl_Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Header1Layout.createSequentialGroup()
                .addComponent(header_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Header1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_GymMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(pnl_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_GymMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1179, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btn_equipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_equipmentMouseClicked
        
        setColor(btn_equipment);
        resetColor(btn_gymMembers);
        resetColor(btn_instructor);
        resetColor(btn_employee);
        try {
            
            equipmentMenu equipment_menu = new equipmentMenu();
            pnl_GymMembers.removeAll();
            pnl_GymMembers.add(equipment_menu).setVisible(true);
            
            header_tab.setText("Equipment");
            equipment_menu.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_equipmentMouseClicked

    private void btn_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_employeeMouseClicked
            
        setColor(btn_employee);
        resetColor(btn_gymMembers);
        resetColor(btn_instructor);
        resetColor(btn_equipment);
        
        try {
           
            employeeMenu employee_menu = new employeeMenu();
            pnl_GymMembers.removeAll();
            pnl_GymMembers.add(employee_menu).setVisible(true);
            
            header_tab.setText("Employee");
            employee_menu.setMaximum(true);
                    
                    } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_employeeMouseClicked

    private void btn_instructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_instructorMouseClicked
        
        setColor(btn_instructor);
        resetColor(btn_gymMembers);
        resetColor(btn_employee);
        resetColor(btn_equipment);
        
        try {           
            instructorMenu instructor_menu = new instructorMenu();
            pnl_GymMembers.removeAll();
            pnl_GymMembers.add(instructor_menu).setVisible(true);
            instructor_menu.setMaximum(true);
            header_tab.setText("Instructor");
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_instructorMouseClicked

    private void btn_gymMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gymMembersMouseClicked
            
        setColor(btn_gymMembers);
        resetColor(btn_instructor);
        resetColor(btn_employee);
        resetColor(btn_equipment);
            
        try {

            memberMenu member_menu = new memberMenu();
            pnl_GymMembers.removeAll();
            pnl_GymMembers.add(member_menu).setVisible(true);
            member_menu.setMaximum(true);
            header_tab.setText("Gym Members");
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_gymMembersMouseClicked

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/title_icon.png")));
    }
    
//    /**
//     * @param args the command line arguments
//     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //Nimbus
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    void setColor(JPanel panel){
        panel.setBackground(new Color(0,212,212));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(251,126,100)); 
    }
    
    
    public void componentResized(ComponentEvent e) {
        memberMenu member_menu = new memberMenu();
        Home h = new Home();
        if (e.getSource() == pnl_GymMembers) {

            member_menu.setBounds(0, 0, h.getContentPane().getWidth() / 4, h.getContentPane().getHeight());
            //yourInternalFrame2.setBounds(yourFrame.getContentPane().getWidth() / 4, 0, yourFrame.getContentPane().getWidth() / 2, yourFrame.getContentPane().getHeight() / 2);

            // and so on
            // also can use yourDesktopPane instead of yourFrame.getContentPane()

        }
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_employee;
    private javax.swing.JPanel btn_equipment;
    private javax.swing.JPanel btn_gymMembers;
    private javax.swing.JPanel btn_instructor;
    private javax.swing.JLabel header_tab;
    private javax.swing.JLabel header_title;
    private javax.swing.JLabel header_title1;
    private javax.swing.JLabel icon_members;
    private javax.swing.JLabel icon_members4;
    private javax.swing.JLabel icon_members5;
    private javax.swing.JLabel icon_members6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnl_GymMembers;
    private javax.swing.JPanel pnl_Header;
    private javax.swing.JPanel pnl_Header1;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
