/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;
import activity.InstructorClass;
import controller.InstructorDAOImp;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Wang
 */
public class instructorMenu extends javax.swing.JInternalFrame {
   

    /**
     * Creates new form memberMenu
     */
    public instructorMenu() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
       Load();
       panelBorder();
       validationError();
       
        jComboBox_InstructorGender.setModel(new DefaultComboBoxModel <> (new String [] {
            " Select Gender ","Male","Female" }));
        
        jTextField_lbl_instructor_total.setEditable(false);
      
    } 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    int searchh;
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_fields = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        validation_instructorID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        validation_instructorFirstName = new javax.swing.JLabel();
        validation_instructorLastName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        validation_instructorEmail = new javax.swing.JLabel();
        jTextField_InstructorEmail = new javax.swing.JTextField();
        jDateChooser_InstructorBirthday = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        validation_instructorBirthday = new javax.swing.JLabel();
        jTextField_InstructorContactNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        validation_instructorContact = new javax.swing.JLabel();
        jTextField_InstructorMName = new javax.swing.JTextField();
        jTextField_InstructorFName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_InstructorID = new javax.swing.JTextField();
        validation_instructorMiddleName = new javax.swing.JLabel();
        jTextField_InstructoAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        validation_instructorAddress = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        validation_instructorGender = new javax.swing.JLabel();
        jComboBox_InstructorGender = new javax.swing.JComboBox<>();
        jTextField_InstructorLName = new javax.swing.JTextField();
        panel_buttons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panel_salary = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_InstructorDuration = new javax.swing.JTextField();
        validation_instructorDuration = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        validation_instructorRate = new javax.swing.JLabel();
        jTextField_InstructorRate = new javax.swing.JTextField();
        jTextField_lbl_instructor_total = new javax.swing.JTextField();
        lbl_instructor_total = new javax.swing.JLabel();
        validation_instructorTotal = new javax.swing.JLabel();
        btn_computeSalary = new javax.swing.JButton();
        panel_instructorlist = new javax.swing.JPanel();
        instructorSearch = new javax.swing.JTextField();
        searchInstructor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_instructor = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(254, 243, 246));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        panel_fields.setBackground(new java.awt.Color(254, 243, 246));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Instructor ID");

        validation_instructorID.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorID.setText("*");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("First Name");

        validation_instructorFirstName.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorFirstName.setText("*");

        validation_instructorLastName.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorLastName.setText("*");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Email");

        validation_instructorEmail.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorEmail.setText("*");

        jTextField_InstructorEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser_InstructorBirthday.setDateFormatString("yyyy-MM-dd");
        jDateChooser_InstructorBirthday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Birthday");

        validation_instructorBirthday.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorBirthday.setText("*");

        jTextField_InstructorContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Contact No.");

        validation_instructorContact.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorContact.setText("*");

        jTextField_InstructorMName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_InstructorFName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Middle Name");

        validation_instructorMiddleName.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorMiddleName.setText("*");

        jTextField_InstructoAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Address");

        validation_instructorAddress.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorAddress.setText("*");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Gender");

        validation_instructorGender.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorGender.setText("*");

        jComboBox_InstructorGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_InstructorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_InstructorGenderActionPerformed(evt);
            }
        });

        jTextField_InstructorLName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_InstructorLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InstructorLNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fieldsLayout = new javax.swing.GroupLayout(panel_fields);
        panel_fields.setLayout(panel_fieldsLayout);
        panel_fieldsLayout.setHorizontalGroup(
            panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_instructorID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_InstructorID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(validation_instructorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_InstructorContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jTextField_InstructorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(validation_instructorBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser_InstructorBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation_instructorMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation_instructorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jTextField_InstructorFName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(6, 6, 6)
                                        .addComponent(validation_instructorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_InstructorMName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation_instructorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_InstructorLName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(validation_instructorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_InstructorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation_instructorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_InstructoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_fieldsLayout.setVerticalGroup(
            panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fieldsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validation_instructorID)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_InstructorID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(validation_instructorFirstName)
                    .addComponent(jLabel9)
                    .addComponent(validation_instructorMiddleName)
                    .addComponent(jLabel3)
                    .addComponent(validation_instructorLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_InstructorFName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_InstructorMName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_InstructorLName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(validation_instructorBirthday))
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(validation_instructorEmail)))
                        .addGroup(panel_fieldsLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(validation_instructorContact))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_InstructorContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_InstructorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser_InstructorBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fieldsLayout.createSequentialGroup()
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(panel_fieldsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(validation_instructorGender)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_InstructorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_InstructoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(validation_instructorAddress)))
                .addContainerGap())
        );

        panel_buttons.setBackground(new java.awt.Color(254, 243, 246));

        jButton1.setBackground(new java.awt.Color(0, 181, 73));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(79, 118, 224));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(174, 13, 16));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/delete.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(240, 194, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_buttonsLayout = new javax.swing.GroupLayout(panel_buttons);
        panel_buttons.setLayout(panel_buttonsLayout);
        panel_buttonsLayout.setHorizontalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_buttonsLayout.setVerticalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_salary.setBackground(new java.awt.Color(254, 243, 246));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Session Duration");

        jTextField_InstructorDuration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        validation_instructorDuration.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorDuration.setText("*");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Session Rate Per Hour");

        validation_instructorRate.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorRate.setText("*");

        jTextField_InstructorRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_lbl_instructor_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_lbl_instructor_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lbl_instructor_totalActionPerformed(evt);
            }
        });

        lbl_instructor_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_instructor_total.setText("Total");

        validation_instructorTotal.setForeground(new java.awt.Color(255, 0, 51));
        validation_instructorTotal.setText("*");

        btn_computeSalary.setText("Compute Salary");
        btn_computeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_computeSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_salaryLayout = new javax.swing.GroupLayout(panel_salary);
        panel_salary.setLayout(panel_salaryLayout);
        panel_salaryLayout.setHorizontalGroup(
            panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_salaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_salaryLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_instructorDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_InstructorDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_salaryLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_instructorRate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(panel_salaryLayout.createSequentialGroup()
                        .addComponent(jTextField_InstructorRate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_computeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_salaryLayout.createSequentialGroup()
                        .addComponent(lbl_instructor_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_instructorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_lbl_instructor_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_salaryLayout.setVerticalGroup(
            panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_salaryLayout.createSequentialGroup()
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_instructor_total)
                        .addComponent(validation_instructorTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(validation_instructorDuration)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(validation_instructorRate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lbl_instructor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_InstructorRate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_InstructorDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_computeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_instructorlist.setBackground(new java.awt.Color(254, 243, 246));

        instructorSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        searchInstructor.setBackground(new java.awt.Color(223, 89, 62));
        searchInstructor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchInstructor.setForeground(new java.awt.Color(255, 255, 255));
        searchInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectGUI/images/search.png"))); // NOI18N
        searchInstructor.setText("Search");
        searchInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInstructorActionPerformed(evt);
            }
        });

        jTable_instructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Instructor ID", "Firstname", "Middlename", "Lastname", "Contact No.", "Email", "Gender", "Birthday", "Address", "Session Duration", "Rate", "Total"
            }
        ));
        jTable_instructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_instructorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_instructor);

        javax.swing.GroupLayout panel_instructorlistLayout = new javax.swing.GroupLayout(panel_instructorlist);
        panel_instructorlist.setLayout(panel_instructorlistLayout);
        panel_instructorlistLayout.setHorizontalGroup(
            panel_instructorlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_instructorlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_instructorlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_instructorlistLayout.createSequentialGroup()
                        .addComponent(instructorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(searchInstructor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_instructorlistLayout.setVerticalGroup(
            panel_instructorlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_instructorlistLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panel_instructorlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_instructorlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_fields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(panel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_fields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_instructorlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_InstructorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_InstructorGenderActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_InstructorGenderActionPerformed

    private void searchInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInstructorActionPerformed
       try{
            
            searchh = Integer.parseInt(instructorSearch.getText());
            InstructorDAOImp dao = new InstructorDAOImp ();
            InstructorClass ic = dao.get(searchh);
            
            jTextField_InstructorID.setText(String.valueOf(ic.getInstructorID()));
            jTextField_InstructorFName.setText(ic.getFirstName());
            jTextField_InstructorMName.setText(ic.getMiddleName());
            jTextField_InstructorLName.setText(ic.getLastName());
            jTextField_InstructorContactNo.setText(String.valueOf(ic.getContactNo()));
            jTextField_InstructorEmail.setText(ic.getEmail());
            jComboBox_InstructorGender.setSelectedItem(ic.getGender());
            Date dateBirth = new SimpleDateFormat ("yyyy-MM-dd").parse(String.valueOf(ic.getBirthday()));
            jDateChooser_InstructorBirthday.setDate(dateBirth);
            jTextField_InstructoAddress.setText(ic.getAddress());
            jTextField_InstructorDuration.setText(String.valueOf(ic.getDuration()));
            jTextField_InstructorRate.setText(String.valueOf(ic.getRate()));
            jTextField_lbl_instructor_total.setText(String.valueOf(ic.getTotalRate()));
            
            
            
            Load();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "No Result!");
        }
    }//GEN-LAST:event_searchInstructorActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTable_instructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_instructorMouseClicked
       try {

            DefaultTableModel RecordTable = (DefaultTableModel)jTable_instructor.getModel();
            int SelectedRows = jTable_instructor.getSelectedRow();
            InstructorDAOImp dao = new InstructorDAOImp ();
            
            searchh = (int) (jTable_instructor.getModel().getValueAt(SelectedRows, 0));
            InstructorClass ic = dao.get(searchh);                      
            
            jTextField_InstructorID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
            jTextField_InstructorFName.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
            jTextField_InstructorMName.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
            jTextField_InstructorLName.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
            jTextField_InstructorContactNo.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
            jTextField_InstructorEmail.setText(RecordTable.getValueAt(SelectedRows, 6).toString()); 
            jComboBox_InstructorGender.setSelectedItem(RecordTable.getValueAt(SelectedRows,7).toString());
            Date dateBirth = new SimpleDateFormat ("yyyy-MM-dd").parse((String)RecordTable.getValueAt(SelectedRows, 8));
            jDateChooser_InstructorBirthday.setDate(dateBirth);
            jTextField_InstructoAddress.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
            jTextField_InstructorDuration.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
            jTextField_InstructorRate.setText(RecordTable.getValueAt(SelectedRows, 11).toString());
            jTextField_lbl_instructor_total.setText(RecordTable.getValueAt(SelectedRows, 12).toString());
            
            Load();
            
        } catch (ParseException ex) {
            Logger.getLogger(instructorMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_instructorMouseClicked

    private void jTextField_lbl_instructor_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lbl_instructor_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lbl_instructor_totalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            
            InstructorClass gym_instructor = new InstructorClass();
            gym_instructor.ComputeTotal();
            int instructor_id = Integer.parseInt(jTextField_InstructorID.getText());
            String instructor_first_name = jTextField_InstructorFName.getText();
            String instructor_middle_name = jTextField_InstructorMName.getText();
            String instructor_last_name = jTextField_InstructorLName.getText();
            String instructor_gender = jComboBox_InstructorGender.getSelectedItem().toString();
            String instructor_birthday = ((JTextField) jDateChooser_InstructorBirthday.getDateEditor().getUiComponent()).getText();
            String instructor_contact = jTextField_InstructorContactNo.getText();
            String instructor_email = jTextField_InstructorEmail.getText();
            String instructor_address = jTextField_InstructoAddress.getText();
            int instructor_duration = Integer.parseInt(jTextField_InstructorDuration.getText());
            double instructor_rate = Double.parseDouble(jTextField_InstructorRate.getText());
            double instructor_total = Double.parseDouble(jTextField_lbl_instructor_total.getText());

            gym_instructor.setInstructorID(instructor_id);
            gym_instructor.setFirstName(instructor_first_name);
            gym_instructor.setMiddleName(instructor_middle_name);
            gym_instructor.setLastName(instructor_last_name);
            gym_instructor.setGender(instructor_gender);
            gym_instructor.setBirthday(instructor_birthday);
            gym_instructor.setContactNo(instructor_contact);
            gym_instructor.setEmail(instructor_email);
            gym_instructor.setAddress(instructor_address);
            gym_instructor.setDuration(instructor_duration);
            gym_instructor.setRate(instructor_rate);
            gym_instructor.setTotalRate(instructor_total);


            InstructorDAOImp instructor_dao = new InstructorDAOImp();
            instructor_dao.save(gym_instructor);
            Load();
            jTextField_InstructorID.setText("");
            jTextField_InstructorFName.setText("");
            jTextField_InstructorMName.setText("");
            jTextField_InstructorLName.setText("");  
            jTextField_InstructorContactNo.setText("");
            jTextField_InstructorEmail.setText("");
            jTextField_InstructoAddress.setText("");
            jComboBox_InstructorGender.setSelectedIndex(0); 
            jDateChooser_InstructorBirthday.setCalendar(null);
            jTextField_InstructorDuration.setText("");
            jTextField_InstructorRate.setText("");
            jTextField_lbl_instructor_total.setText("");

            jTextField_InstructorID.requestFocus();   
            validationError();
        }
        catch(Exception e){
            txtFieldValidation();
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try{
            InstructorClass instructor = new InstructorClass();
            
            int instructor_id = Integer.parseInt(jTextField_InstructorID.getText());
            String instructor_first_name = jTextField_InstructorFName.getText();
            String instructor_middle_name = jTextField_InstructorMName.getText();
            String instructor_last_name = jTextField_InstructorLName.getText();
            String instructor_contact = jTextField_InstructorContactNo.getText();
            String instructor_email = jTextField_InstructorEmail.getText();
            String instructor_gender = jComboBox_InstructorGender.getSelectedItem().toString();
            String instructor_birthday = ((JTextField) jDateChooser_InstructorBirthday.getDateEditor().getUiComponent()).getText();
            String instructor_address = jTextField_InstructoAddress.getText();
            int instructor_duration = Integer.parseInt(jTextField_InstructorDuration.getText());
            double instructor_rate = Double.parseDouble(jTextField_InstructorRate.getText());
            double instructor_total = Double.parseDouble(jTextField_lbl_instructor_total.getText());

            instructor.setInstructorID(instructor_id);
            instructor.setFirstName(instructor_first_name);
            instructor.setMiddleName(instructor_middle_name);
            instructor.setLastName(instructor_last_name);
            instructor.setContactNo(instructor_contact);
            instructor.setGender(instructor_gender);
            instructor.setBirthday(instructor_birthday);
            instructor.setEmail(instructor_email);
            instructor.setAddress(instructor_address);
            instructor.setDuration(instructor_duration);
            instructor.setRate(instructor_rate);
            instructor.setTotalRate(instructor_total);
            

            instructor.setId(searchh);
            InstructorDAOImp instructor_dao = new InstructorDAOImp();
            instructor_dao.update(instructor);
            Load();
            jTextField_InstructorID.setText("");
            jTextField_InstructorFName.setText("");
            jTextField_InstructorMName.setText("");
            jTextField_InstructorLName.setText("");  
            jTextField_InstructorContactNo.setText("");
            jTextField_InstructorEmail.setText("");
            jTextField_InstructoAddress.setText("");
            jComboBox_InstructorGender.setSelectedItem(null); 
            jDateChooser_InstructorBirthday.setCalendar(null);
            jTextField_InstructorDuration.setText("");
            jTextField_InstructorRate.setText("");
            jTextField_lbl_instructor_total.setText("");

            jTextField_InstructorID.requestFocus();      
            validationError();
        }catch(Exception e){
            txtFieldValidation();
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        InstructorClass instructor = new InstructorClass();

        instructor.setId(searchh);
        InstructorDAOImp instructor_dao = new InstructorDAOImp();
        instructor_dao.delete(instructor);
        Load();
        jTextField_InstructorID.setText("");
        jTextField_InstructorFName.setText("");
        jTextField_InstructorMName.setText("");
        jTextField_InstructorLName.setText("");  
        jTextField_InstructorContactNo.setText("");
        jTextField_InstructorEmail.setText("");
        jTextField_InstructoAddress.setText("");
        jComboBox_InstructorGender.setSelectedItem(null); 
        jDateChooser_InstructorBirthday.setDateFormatString("");
        jTextField_InstructorDuration.setText("");
        jTextField_InstructorRate.setText("");
        jTextField_lbl_instructor_total.setText("");

        jTextField_InstructorID.requestFocus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jTextField_InstructorID.setText("");
        jTextField_InstructorFName.setText("");
        jTextField_InstructorMName.setText("");
        jTextField_InstructorLName.setText("");  
        jTextField_InstructorContactNo.setText("");
        jTextField_InstructorEmail.setText("");
        jTextField_InstructoAddress.setText("");
        jComboBox_InstructorGender.setSelectedItem(null); 
        jDateChooser_InstructorBirthday.setDateFormatString("");
        jTextField_InstructorDuration.setText("");
        jTextField_InstructorRate.setText("");
        jTextField_lbl_instructor_total.setText("");
        
        validationError();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_computeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_computeSalaryActionPerformed
          InstructorClass instructor = new InstructorClass();
          instructor.setDuration(Integer.parseInt(jTextField_InstructorDuration.getText()));
          instructor.setRate(Double.parseDouble(jTextField_InstructorRate.getText()));
          instructor.ComputeTotal();
          jTextField_lbl_instructor_total.setText(instructor.getTotal()+"");
    }//GEN-LAST:event_btn_computeSalaryActionPerformed

    private void jTextField_InstructorLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InstructorLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InstructorLNameActionPerformed

     public void tableSize () {
        
    jTable_instructor.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
    
        for (int column = 0; column < jTable_instructor.getColumnCount(); column++) {
            TableColumn tableColumn = jTable_instructor.getColumnModel().getColumn(column);
//            int preferredWidth = tableColumn.getMinWidth();
            int preferredWidth = 100;
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < jTable_instructor.getRowCount(); row++)
            {
                TableCellRenderer cellRenderer = jTable_instructor.getCellRenderer(row, column);
                Component c = jTable_instructor.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + jTable_instructor.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth >= maxWidth)
                {
                    preferredWidth = maxWidth;
                    break;
                }
        }

        tableColumn.setPreferredWidth( preferredWidth );

        }      
    }

    
    public void Load() {
        InstructorDAOImp instructor_dao = new InstructorDAOImp();
        List<InstructorClass> list = instructor_dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable_instructor.getModel();
        DFT.setRowCount(0);
        for(InstructorClass ic: list)
        {
            int id = ic.getId();
            int insID = ic.getInstructorID();
            String first_name = ic.getFirstName();
            String middle_name = ic.getMiddleName();
            String last_name = ic.getLastName();
            String contact = ic.getContactNo();
            String ins_email = ic.getEmail();
            String gender = ic.getGender();
            String birthday = ic.getBirthday();
            String address = ic.getAddress();
            int ins_duration = ic.getDuration();
            double ins_rate = ic.getRate();
            double ins_total = ic.getTotal();

            DFT.addRow(new Object[]{id, insID, first_name, middle_name, last_name,contact, ins_email, gender, birthday,  address,
              ins_duration, ins_rate, ins_total});
        }    
  
    }
    
    private void txtFieldValidation() {
        if(jTextField_InstructorID.getText().trim().isEmpty()){
            validation_instructorID.setVisible(true);
        }
        
        if(jTextField_InstructorFName.getText().trim().isEmpty()){
            validation_instructorFirstName.setVisible(true);
        }  
        
        if(jTextField_InstructorMName.getText().trim().isEmpty()){
            validation_instructorMiddleName.setVisible(true);
        }
        
        if(jTextField_InstructorLName.getText().trim().isEmpty()){
            validation_instructorLastName.setVisible(true);
        }
        
        if(jTextField_InstructorContactNo.getText().trim().isEmpty()){
            validation_instructorContact.setVisible(true);
        }     
        
        if(jComboBox_InstructorGender.getSelectedIndex()==0){
            validation_instructorGender.setVisible(true);
        }   
        
        if(jDateChooser_InstructorBirthday.getDate() == null){
            validation_instructorBirthday.setVisible(true);
        }  
        
        if(jTextField_InstructorEmail.getText().trim().isEmpty()){
            validation_instructorEmail.setVisible(true);
        }         

        if(jTextField_InstructoAddress.getText().trim().isEmpty()){          
            validation_instructorAddress.setVisible(true);            
        }
        
        if(jTextField_InstructorDuration.getText().trim().isEmpty()){          
            validation_instructorDuration.setVisible(true);            
        }
         
        if(jTextField_InstructorRate.getText().trim().isEmpty()){          
            validation_instructorRate.setVisible(true);            
        }
         
        if(jTextField_lbl_instructor_total.getText().trim().isEmpty()){          
            validation_instructorTotal.setVisible(true);            
        }
  
    }
    private void validationError() {
            validation_instructorID.setVisible(false);
            validation_instructorFirstName.setVisible(false);
            validation_instructorMiddleName.setVisible(false);
            validation_instructorLastName.setVisible(false);
            validation_instructorContact.setVisible(false);
            validation_instructorGender.setVisible(false);
            validation_instructorBirthday.setVisible(false);
            validation_instructorEmail.setVisible(false);
            validation_instructorAddress.setVisible(false);
            validation_instructorDuration.setVisible(false);
            validation_instructorRate.setVisible(false);
            validation_instructorTotal.setVisible(false);    
    }
    
                
    
    public void panelBorder(){
        
       panel_fields.setBorder(new TitledBorder(new LineBorder(new Color (16, 82, 142)), 
                "Instructor Info", TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.CENTER, new Font("SansSerif", Font.PLAIN, 12), new Color (16, 82, 142)));
       
       panel_salary.setBorder(new TitledBorder(new LineBorder(new Color (16, 82, 142)), 
                "Instructor Salary", TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.CENTER, new Font("SansSerif", Font.PLAIN, 12), new Color (16, 82, 142))); 
       
       panel_instructorlist.setBorder(new TitledBorder(new LineBorder(new Color (16, 82, 142)), 
                "Instructor List", TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.CENTER, new Font("SansSerif", Font.PLAIN, 12), new Color (16, 82, 142)));
       
    }            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_computeSalary;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField instructorSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_InstructorGender;
    private com.toedter.calendar.JDateChooser jDateChooser_InstructorBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_instructor;
    private javax.swing.JTextField jTextField_InstructoAddress;
    private javax.swing.JTextField jTextField_InstructorContactNo;
    private javax.swing.JTextField jTextField_InstructorDuration;
    private javax.swing.JTextField jTextField_InstructorEmail;
    private javax.swing.JTextField jTextField_InstructorFName;
    private javax.swing.JTextField jTextField_InstructorID;
    private javax.swing.JTextField jTextField_InstructorLName;
    private javax.swing.JTextField jTextField_InstructorMName;
    private javax.swing.JTextField jTextField_InstructorRate;
    private javax.swing.JTextField jTextField_lbl_instructor_total;
    private javax.swing.JLabel lbl_instructor_total;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JPanel panel_fields;
    private javax.swing.JPanel panel_instructorlist;
    private javax.swing.JPanel panel_salary;
    private javax.swing.JButton searchInstructor;
    private javax.swing.JLabel validation_instructorAddress;
    private javax.swing.JLabel validation_instructorBirthday;
    private javax.swing.JLabel validation_instructorContact;
    private javax.swing.JLabel validation_instructorDuration;
    private javax.swing.JLabel validation_instructorEmail;
    private javax.swing.JLabel validation_instructorFirstName;
    private javax.swing.JLabel validation_instructorGender;
    private javax.swing.JLabel validation_instructorID;
    private javax.swing.JLabel validation_instructorLastName;
    private javax.swing.JLabel validation_instructorMiddleName;
    private javax.swing.JLabel validation_instructorRate;
    private javax.swing.JLabel validation_instructorTotal;
    // End of variables declaration//GEN-END:variables
}
